version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - node-nginx
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=node
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - node-nginx

  web:
    build:
      context: nginx
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - node-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - app

networks:
  node-nginx:
    driver: bridge
